### ISSUE TITLE
Show page positions for page keywords

### ISSUE THREAD

**Issue by zveer** [5starsmedia/paphos-analytics#2]
On "page statistic" show page positions for page keywords in Yandex and Google below this graph:
![image](https://cloud.githubusercontent.com/assets/14909087/15643614/08fd12be-2657-11e6-87d9-efb64a287267.png)

**Comment by polluxx** [comment]
А якщо ключових слів немає дл цієї сторінки? Виводити кількість нових юзерів, як було до цього?

**Comment by zveer** [comment]
кількість юзерів виводити в будь-якому випадку, якшо нема фраз - то просто не виводити

**Comment by polluxx** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/4069748/15654044/9a12d468-2699-11e6-85c3-7f9298bdf793.png)

реально данних по ключам ГА не віддасть багато, виводити пересічення сторінки і пошукових запитів?

**Comment by polluxx** [comment]
я мабуть не зовсім точно зрозумів, фрази мабуть не ті, які витягнуті з яндекса, а ті, що віддаються по цій сторінкі в гуглі, так? нот сет і нот провайдед не показувати?

**Comment by polluxx** [comment]
готово
